### ISSUE TITLE
Updating topic mastery: when revising progress page, mastery drops

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#9] opened 2018-11-01 15:37 UTC
There is a method called computeMastery() that does all the computation to update topic mastery based on performance on a problem.

Now, I realized that when revisiting the Student Progress Page (SPP) often (for instance, go to SPP once, click continue, don't solve the problem, and immediately go back to the SPP, drops the mastery.

This shouldn't be the case because there was no attempt made on the problem, just a skip. It should remain the same.

We should debug and see what is making this drop in mastery.

**Comment by nsmenon** [comment] 2019-01-28 18:41
Unable to reproduce. Closing it for now

**Closed by nsmenon** 2019-01-28 18:41 UTC
Labels: ms-bug
